### ISSUE TITLE
React dev tools interfere with the Trello authentication window

### ISSUE THREAD

**Issue by odzb** [fiatjaf/trello-web#1]
I use React dev tools for Chrome, and they pass their own messages to the page, which makes it impossible to authorize in Trello using the popup window. Trello just receives "[object Object]" as the token and fails.

The fix is simple: add a check for whether e.data is a string.

```
      window.addEventListener('message', function(e) {
        if (typeof e.data === 'string') {
          clearTimeout(timeout);
          popup.close();
          self.token = e.data;
          return resolve();
        }
      });
`
```

**Comment by fiatjaf** [comment]
Thank you very much. I can fix this week, but it would be much better if you submitted a PR. Could you?

**Comment by odzb** [comment]
Sure I can, thanks for your response.
