### ISSUE TITLE
No LICENSE file included with the NPM module

### ISSUE THREAD

**Issue by odzb** [fiatjaf/trello-web#2]
The **trello-browser** module is currently failing our company's legal criteria because it doesn't include its full license text within the npm module. Simply stating that the license is MIT is not enough because it's not clear (from the legal point of view) what EXACTLY do you mean by "MIT".

Thanks in advance if you could fix this.

**Comment by fiatjaf** [comment]
Can you please submit a PR with the full text of the MIT license in the LICENSE file?

**Comment by odzb** [comment]
I'm not sure I can do it for you for legal reasons. The text is at http://opensource.org/licenses/MIT , please copy it and fill in the years and your name. Thanks a lot.

**Comment by fiatjaf** [comment]
Done in https://github.com/fiatjaf/trello-browser/commit/3b6e07a290c5c4cf6e66719a18746effa730f28c

I have also published a new version to npm.
Thanks again.
